name: Checks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
    - name: Build
      run: |
        chmod +x build
        ./build

